### PR TITLE
Feature/10 migrate to GitHub actions

### LINKED ISSUE #10: Migrate to GitHub Actions
**Is your feature request related to a problem? Please describe.**
Due to the platform migration to GitHub, we currently lost the CI tools including code testing.

**Describe the solution you'd like**
(Re-)setup the CI tools for GitHub Actions.

### PR DESCRIPTION
**Pull request by tkokada**
A draft of "GitHub Actions" impelmentation is requested to fix #10 .

Currenly this supports OS: ubuntu-20.04 and Python-3.8. Unit tests, integuration tests and resume tests are passed. But it still contains an issue that resume tests sometime suspend. This issue should be posted independently.

The reason why unit tests failed, is the lack of tests/test_data/work directory. The contents of tests/test_data may be reconsidered to fit latest codes.

### CODE REVIEW

**Comment by yoshipon** [comment]
Thank you for setting up the automatic testing! The commit seems to have so many (>= 450) files including pickle files. Is it intended?

**Comment by tkokada** [comment]
Yes, as I described, the commit contains a lack of directory. I just copied it from the previous version management web site.

It happens why the .gitignore file ignores the name of "work" directory. But work directory is in tests/test_data directory. So Onishi's commit was ignored to add work directory. I just use "-f" option for "git add". Shall we remove "work" from .gitignore? But I don't think so...

**Comment by yoshipon** [comment]
Thanks! I see...
So, how about changing `work/` in `.gitignore` to `/work/` or adding `/tests/test_data/work`?

I want the same thing not to happen again.

**Comment by tkokada** [comment]
Sounds good, why don't we choose /work/? It's simple.

**Comment by yoshipon** [comment]
I'm glad we agree :) Could you include the update of .gitignore to this PR...?

**Comment by tkokada** [comment]
Sure, I may update it tomorrow.

**Review by yoshipon — APPROVED** [review]
LGTM! Thanks!

**Comment by yoshipon** [comment]
@aramoto99 Do you have any opinions?

**Comment by aramoto99** [comment]
I am concerned that the data for the test is outdated.
There is an hp filename with alphabets, but it is not the current spec. Currently it is only numbers.
(e.g. OBd.hp)
However, this is not a critical issue, as it is not a problem in testing (not using it for testing). Once again, deletion is not necessary. (However, it will need to be addressed at some point.)

**Comment by yoshipon** [comment]
@aramoto99 Thank you for your comment. 
>  it will need to be addressed at some point.

I'd like to clarify what should be addressed. The best is to remove OBd.hp (and others as well) ...?

**Pull request merged**
